### ISSUE TITLE
Command ros2 launch arm_api2 moveit2_iface.launch.py robot_name:="ur" not working

### ISSUE THREAD

**Issue by nishantjb1** [CroboticSolutions/arm_api2#8]
## Environment
* OS Version: <!Ubuntu 22.04 >
* OS Installation: <!WSL>
* Docker or manual installation?: <!Manual-RO2-Humble>

## Description
* Expected behavior: The command is expected to launch the selected robot's (ur in my case)  yaml files
* Actual behavior: got "bad conversion" error

## Steps to reproduce
1. Clone the package in src
2. Clone ur_robot_driver and ur_simulation_gz
3. Build the workspace. (The build was successful)
4. Command ur_sim or ros2 launch ur_simulation_gz ur_sim_control.launch.py ur_type:="ur10" does not work properly. On running gazebo quick start page is launched 
<img width="484" alt="image" src="https://github.com/user-attachments/assets/90685792-1ef6-4491-9881-c5db4cd91962">
On selecting any world, an empti gazebo file is launched and rviz is launched in which bot can be seen but the both gazebo and rviz crash after 5 secs.
5. After that ur_moveit_config is working correctly and robot is launched in rviz 
6. Then after running this command "ros2 launch arm_api2 moveit2_iface.launch.py robot_name:="ur"" I get the following error

## Output
<details>
nemesis@Nemesis:~$ ros2 launch arm_api2 moveit2_iface.launch.py robot_name:="ur"
[INFO] [launch]: All log files can be found below /home/nemesis/.ros/log/2024-10-17-10-16-38-896877-Nemesis-5719
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [moveit2_iface-1]: process started with pid [5720]
[INFO] [joy_node-2]: process started with pid [5722]
[INFO] [joy_ctl-3]: process started with pid [5724]
[joy_ctl-3] [INFO] [1729140399.024594987] [joy_ctl]: Initialized joy_ctl
[moveit2_iface-1] [INFO] [1729140399.061498324] [moveit2_iface]: Loaded config!
[moveit2_iface-1] [INFO] [1729140399.061769168] [moveit2_iface]: Config yaml path is: /home/nemesis/workspace/ros_ur_driver/install/arm_api2/share/arm_api2/config/ur/ur_sim.yaml
[moveit2_iface-1] [INFO] [1729140399.064139964] [moveit2_iface]: Initialized publishers!
[moveit2_iface-1] [INFO] [1729140399.067390937] [moveit2_iface]: Initialized subscribers!
[moveit2_iface-1] terminate called after throwing an instance of 'YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
[moveit2_iface-1]   what():  bad conversion
[ERROR] [moveit2_iface-1]: process has died [pid 5720, exit code -6, cmd '/home/nemesis/workspace/ros_ur_driver/install/arm_api2/lib/arm_api2/moveit2_iface --ros-args --params-file /tmp/launch_params_60b6xeid --params-file /tmp/launch_params_vcyng9ay --params-file /tmp/launch_params_vopc509a --params-file /tmp/launch_params_5cekn6co --params-file /tmp/launch_params_jxgd9c5c --params-file /tmp/launch_params_pug3p75b'].
</details>

## Screenshots
<img width="957" alt="image" src="https://github.com/user-attachments/assets/802dbc2f-aafe-4497-9c94-be0b3fdb0d2f">

**Comment by fzoric8** [comment]
Hi @nishantjb1 , 

Thank you for the report. 
I've tried to reproduce the error, and same thing happens to me. 

As I changed some keys for more clarity, this one remained same for the UR. 
Therefore, it needed fixing. 

I've updated config file and pushed it to the `master` branch. 

You need to pull the updates, and try again. 
Please let me know if it works. 

From the side of the `gazebo`, I'm not really sure what's the problem. Just one notice, I'm using [this](https://github.com/CroboticSolutions/Universal_Robots_ROS2_GZ_Simulation) as driver for the `UR`, and [this repository](https://github.com/CroboticSolutions/Universal_Robots_ROS2_GZ_Simulation) for simulation of the robot. 

Also, If you want to be sure to use same environment as me, check out this [Dockerfile](https://github.com/CroboticSolutions/docker_files/tree/master/ros2/humble/kinova). 

Let me know how it goes!

**Comment by nishantjb1** [comment]
Thank you!
